language: go
sudo: false

go:
  - 1.5

env:
  - GO15VENDOREXPERIMENT=1

install:
  - go install -race -v std
  - go get -race -t -v ./...
  - go install -race -v ./...

script:
  - go test -cpu=2 -race ./...
