language: go
sudo: false

go:
  - 1.5

env:
  - GO15VENDOREXPERIMENT=1
  - GO15VENDOREXPERIMENT=0

matrix:
  allow_failures:
    - GO15VENDOREXPERIMENT=0

before_install:
  - test "$GO15VENDOREXPERIMENT" == "0" && rm -rf vendor

install:
  - go install -race -v std
  - go get -race -t -v ./...
  - go install -race -v ./...

script:
  - go test -cpu=2 -race ./...
