language: go

go:
  - 1.4

before_install:
  - go get -v golang.org/x/tools/cmd/vet

install:
  - go install -race -v std
  - go get -race -t -v ./...
  - go install -race -v ./...

script:
  - go vet ./...
  - go test -cpu=2 -race -v ./...
